version: "3.6"

services:
  ijuice:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "24707"
      - "127.0.0.1:24708:24708"
  electrumx:
    image: lukechilds/electrumx:v1.15.0
    ports:
      - "50001"
      - "50002"
    environment:
        COIN: "Komodo"
        DAEMON_URL: "http://changeuser:changepassword@ijuice:24708"
  litewalletmiddleware:
    image: coingateways/atomicorderbook:0.9.2
    ports:
      - "127.0.0.1:7780:7780"
      - "8001:8001"
    environment:
      - MMBOT_URL: "http://EXTERNAL_IP:7780"
      - ME_PUBLIC: "false"
      - ME_PRIVATE: "true"
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
