version: "3.7"

services:
  ijuice-komodo-node:
    build:
      context: ./ijuice-komodo-node
      args:
        - IJUICE_DATA_PATH=${DATA_PATH}/${AC_NAME}
    image: ijuice-komodo-node:test
    environment:
      - AC_CC=2
      - AC_PUBKEY=038afbc819aecfb3d65acdf270f755c9279d69d4a27293f10889264b8bd6c1fae2
      - AC_REWARD=10000
      - AC_SUPPLY=1000
      - IJUICE_DATA_PATH=${DATA_PATH}/${AC_NAME}
      - JUICYCHAIN_TEST_NODE=144.76.148.154
    entrypoint:
      - "bash"
      - "-c"
      - |
        /opt/komodo/komodo/src/komodod \
        -ac_cc=$${AC_CC} \
        -ac_name=${AC_NAME} \
        -ac_pubkey=$${AC_PUBKEY} \
        -ac_reward=$${AC_REWARD} \
        -ac_supply=$${AC_SUPPLY} \
        -addnode=$${JUICYCHAIN_TEST_NODE} \
        -datadir=$${IJUICE_DATA_PATH} \
        -rpcallowip=${DOCKER_KOMODO_NETWORK_SUBNET} \
        -rpcallowip=127.0.0.1 \
        -rpcbind=0.0.0.0 \
        -rpcpassword=${IJUICE_KOMODO_NODE_PASSWORD} \
        -rpcport=24708 \
        -rpcuser=${IJUICE_KOMODO_NODE_USERNAME} \
        -server=1\
        -timeout=18000 \
        -txindex=1 \
        -blocknotify="/opt/komodo/customer-smartchain-nodes-blocknotify/jobs.sh %s" \
        -pubkey=02db69eaad486fb69ac905a771e40b97dcfecbae0a0cc040616fe81a3a05827564
    ports:
      - "24707:24707"
      - "24708:24708"
    networks:
      komodo:
          ipv4_address: ${IJUICE_KOMODO_NODE_IPV4_ADDR}
    volumes:
      - ./ijuice-komodo-node/data:${DATA_PATH}/${AC_NAME}
networks:
  komodo:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_KOMODO_NETWORK_SUBNET}
