version: "3.7"

services:
  juicychain-api:
    build:
      context: ./juicychain-api
      args:
        ENV: dev
    command: python manage.py runserver 0.0.0.0:8999
    environment:
      - DJANGO_HOST=*
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./juicychain-api/src/:/code
    ports:
      - "8999:8999"
    links:
      - db:db
    depends_on:
      - db
    networks:
      komodo:
          ipv4_address: ${JUICYCHAIN_API_IPV4_ADDR}
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      komodo:
        ipv4_address: ${POSTGRES_IPV4_ADDR}
networks:
  komodo:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_KOMODO_SMARTCHAIN_NETWORK_SUBNET}
